version: '3.7'
services:
  web:
    build: .
    command: bundle exec rails s -e development -p 3000 -b '0.0.0.0'
    entrypoint: ./docker-entrypoint.sh
    volumes:
      - .:/app
      - bundler-data:/usr/local/bundle
    ports:
      - "3000:3000"
      - "3306:3306"

volumes:
  bundler-data: