all:
	cd iret; make
	cd BioC; make
	cd BioC-SAMPLE; make
	cd BioC-APPL-ABBR; make
	cd BioC-APPL-SENT; make
	cd BioC-APPL-TOKEN; make
	cd BioC-CORPUS-BioNLP09; make

test:
	cd BioC-SAMPLE; make test
	cd BioC-APPL-ABBR; make test
	cd BioC-APPL-SENT; make test
	cd BioC-APPL-TOKEN; make test
	cd BioC-CORPUS-BioNLP09; make test

clean:
	cd iret; make clean
	cd BioC; make clean
	cd BioC-SAMPLE; make clean
	cd BioC-APPL-ABBR; make clean
	cd BioC-APPL-SENT; make clean
	cd BioC-APPL-TOKEN; make clean
	cd BioC-CORPUS-BioNLP09; make clean
