DEBUG=-g

BIOC=../BioC

IRET=../iret

CPPFLAGS = -g `xml2-config --cflags` -I$(BIOC) -I$(IRET)
LDFLAGS = -g `xml2-config --libs` -L$(BIOC) -L$(IRET) -lBioC -liret

PGMS=ascii_collection print_collection print_collection_reader

all: $(PGMS)

test:
	./print_collection collection.xml | diff -q collection.out -
	./ascii_collection collection.xml | diff -q ascii.xml -
	./print_collection_reader collection.xml | diff -q collection.out -
	xmllint --noout --valid *.xml

%: %.cpp
	$(CXX) -c $(CPPFLAGS) $^
	$(CXX) -o $@ $@.o $(LDFLAGS)

%.o:	%.cpp
	$(CXX) -c $(CPPFLAGS) $^

%:	%.o
	$(CXX) -o $@ $^ $(LDFLAGS)

clean: 
	rm $(PGMS) *.o
